title: FloatNote Documentation
description: Official documentation for FloatNote - Intelligent note-taking app
theme: just-the-docs
url: https://your-github-username.github.io/floatnote-docs
color_scheme: light

# Custom colors
palette:
  primary: "#333333"
  accent: "#fb535a"
  background: "#ffffff"
  text: "#333333"
  link: "#387ca4"

# Enable search
search_enabled: true

# Auxiliary links for the top nav
aux_links:
  "FloatNote Website":
    - "https://ryacy.solutions"
  "Support":
    - "mailto:support@ryacy.com"

# Enable copy code button
enable_copy_code_button: true

nav_order: 1
nav_links:
  - title: macOS Installation
    url: /installation/macos/  # Use directory-style URL

# Footer content
footer_content: |
  <p>Copyright &copy; 2024 Ryacy Solutions. All rights reserved.</p>
  <p><a href="https://ryacy.solutions" style="color: #387ca4;">Visit FloatNote Website</a></p>
